### ISSUE TITLE
"TypeError: allocator undefined for Proc" after upgrading of rails to 4.2

### ISSUE THREAD

**Issue by alexandrz** [philostler/rspec-sidekiq#93]
`expect(Car.method :open).to be_delayed(car.id)` raises `TypeError: allocator undefined for Proc` exception.

It happened with rspec-sidekiq 2.0.0 and upgrading to 2.2.0 hasn't resolved the issue.

**Comment by alexandrz** [comment]
Backtrace:

```
     # /rspec-sidekiq-2.2.0/lib/rspec/sidekiq/matchers/be_delayed.rb:61:in `block in find_job'
     # /rspec-sidekiq-2.2.0/lib/rspec/sidekiq/matchers/be_delayed.rb:60:in `each'
     # /rspec-sidekiq-2.2.0/lib/rspec/sidekiq/matchers/be_delayed.rb:60:in `find'
     # /rspec-sidekiq-2.2.0/lib/rspec/sidekiq/matchers/be_delayed.rb:60:in `find_job'
     # /rspec-sidekiq-2.2.0/lib/rspec/sidekiq/matchers/be_delayed.rb:34:in `matches?'
```

**Comment by alexandrz** [comment]
It happened because we passed AR objects as parameters to jobs
